### ISSUE TITLE
Vagrant is unable to provision using Chef, missing cookbook

### ISSUE THREAD

**Issue by dennisdegreef** [devbootcamps/development-environment#1]
```
Generated at 2015-07-12 14:02:09 +0000
Chef::Exceptions::CookbookNotFound: Cookbook apt not found. If you're loading apt from another cookbook, make sure you configure the dependency in your metadata
/opt/chef/embedded/apps/chef/lib/chef/cookbook/cookbook_collection.rb:38:in `block in initialize'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.5.0/lib/ohai/mash.rb:77:in `yield'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.5.0/lib/ohai/mash.rb:77:in `default'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.5.0/lib/ohai/mash.rb:77:in `default'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:277:in `[]'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:277:in `each_cookbook_dep'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:255:in `add_cookbook_with_deps'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:88:in `block in cookbook_order'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:86:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:86:in `cookbook_order'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:98:in `compile_libraries'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:71:in `compile'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:97:in `load'
/opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:486:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:266:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:247:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:55:in `load'
/usr/bin/chef-solo:55:in `<main>'
```

**Comment by wearethefoos** [comment]
Did you use the Vagrantfile in the simple setup? https://raw.githubusercontent.com/devbootcamps/development-environment/master/simple-setup/Vagrantfile

**Comment by dennisdegreef** [comment]
Nope, the one at the same level as the `Cheffile` and `README.md`

**Comment by dennisdegreef** [comment]
As I'm debugging, it seems that it doesn't install the dependencies in the Cheffile? (Haven't used chef before for provisioning, but am experienced with puppet, ansible, docker)

**Comment by wearethefoos** [comment]
I think that's because you're missing some Vagrant plugins:

Does this README version work for you? https://github.com/devbootcamps/development-environment/blob/5f9ad5904e4b8faf88863eb73f16408023c08f15/README.md

**Comment by dennisdegreef** [comment]
I guess I was missing the two vagrant plugins, it does a lot more now :)

```
$ CHEF_LOG=debug vagrant provision
==> default: Installing Chef cookbooks with Librarian-Chef...
```

Let's see how it goes

**Comment by wearethefoos** [comment]
:+1:

**Comment by dennisdegreef** [comment]
It now is bugging me about 

```
Shared folders that Chef requires are missing on the virtual machine.
This is usually due to configuration changing after already booting the
machine. The fix is to run a `vagrant reload` so that the proper shared
folders will be prepared and mounted on the VM.
```

I'll try to resolve the issue, and see if it works after a `vagrant destroy` and `vagrant up` again.
It's also now integrating the guess additions since the plugins (with a `vagrant reload`).

I'll get back to you if only installing the two plugins did the trick, or more was required.

**Comment by wearethefoos** [comment]
That's a Vagrant bug, you can get around it with:

``` bash
rm .vagrant/machines/default/virtualbox/synced_folders
vagrant reload --provision
```

**Comment by dennisdegreef** [comment]
Ah, too late... `vagrant destroy`ed it already :+1:
Thanks! Didn't know about that one

**Comment by dennisdegreef** [comment]
Well, goes a lot better... but now Ubuntu's keyserver is timing out? Looks like the key-server is working just fine... It appears that me being on the eduroam network is blocking outgoing traffic to port 11371 :-1: 

```
==> default: [2015-07-12T14:56:06+00:00] ERROR: apt_repository[node.js] (nodejs::repo line 7) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[install-key 1655a0ab68576280] (/tmp/vagrant-chef/deb6bed010119535a9058838911bab2b/cookbooks/apt/providers/repository.rb line 28) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
==> default: ---- Begin output of apt-key adv --keyserver keyserver.ubuntu.com --recv 1655a0ab68576280 ----
==> default: STDOUT: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.IX0C7T6cj5 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv 1655a0ab68576280
==> default: STDERR: gpg: requesting key 68576280 from hkp server keyserver.ubuntu.com
==> default: gpg: keyserver timed out
==> default: gpg: keyserver receive failed: keyserver error
==> default: ---- End output of apt-key adv --keyserver keyserver.ubuntu.com --recv 1655a0ab68576280 ----
==> default: Ran apt-key adv --keyserver keyserver.ubuntu.com --recv 1655a0ab68576280 returned 2
```

**Comment by wearethefoos** [comment]
ah yeah that's unfortunate :cry:

**Comment by dennisdegreef** [comment]
Did it work? :)
